### ISSUE TITLE
Possible rounding issue

### ISSUE THREAD

**Issue by producerism** [martinlindhe/unit#2]
FromFahrenheit(72.0).Fahrenheit()

results in 72.00000000000006

What would be the best way to ensure that it would come back out as 72.0, so that the values could be compared as equal?

**Comment by martinlindhe** [comment]
This is an artifact of the library using float64 for fast calculations. For general information about this issue, here's a recommended read: https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

The math/big golang core package [1] has some stuff for dealing with arbitrary precision, but when I wrote this lib, there wasn't yet support for a "decimal" data type, so I stuck with float64.
I have not investigated if things have changed since then.

1: https://golang.org/pkg/math/big

**Comment by martinlindhe** [comment]
Regarding your question about equality. The issue is rather 72.00000000000006 and 72.0 is not equal, so they wont compare as such.
If you dont care too much about the precision, you could for example convert the float values to integers and compare those.

**Comment by martinlindhe** [comment]
Maybe we should put a mention/caution of float64 being used in the README, what do you think?

**Comment by martinlindhe** [comment]
Added a note about this in the README

**Comment by producerism** [comment]
Thanks, good idea adding to the README. For my issue, I just ended up adding a rounding function where I can specify the precision before doing a comparison.
