### ISSUE TITLE
kg should be the base unit of mass

### ISSUE THREAD

**Issue by parnmatt** [martinlindhe/unit#7]
To be a bit of a nitpick; the 7 SI base units are:
- **length**: m, *metre*
- **mass:** kg, *kilogram*
- **time:** s, *second*
- **current:** A, *Ampere*
- **temperature:** K, *Kelvin*
- **substance:** mol, *mole*
- **luminous intensity:** cd, *candela*

Thus, the kilogram should be defined as `1e0` and gram `kilogram * 1e-3`.

**Comment by martinlindhe** [comment]
I'm convinced!
possible to make a patch? else, i'll have a look when i get some free time

/m

**Comment by parnmatt** [comment]
Sure will do tomorrow, possibly.

Now if users of your package have followed your examples, it shouldn't need to change their code; unless they are marshaling the constants; thus a *potential* breaking change. A note should be made, making users aware of this change too.

**Comment by martinlindhe** [comment]
I've been thinking more of this.
I do agree it makes sense to follow the SI conventions, but I am also a bit scared of breaking stuff with such a change. Consider someone stored a calculated result somewhere, it would not match after such a change.

We could do a version bump to 0.2.x and break compatibility for resolving this, and people have the ability to vendor a 0.1.x release if they depend on this.

If you come up with a PR it will likely linger for a couple of days due to this, but it is very appreciated!

**Comment by martinlindhe** [comment]
Looking further into this, i got reminded about the original reason for using gram as a base for mass:

```
Because SI prefixes may not be concatenated (serially linked) within the name or symbol for a unit of measure, SI prefixes are used with the gram, not the kilogram, which already has a prefix as part of its name. For instance, one-millionth of a kilogram is 1 mg (one milligram), not 1 µkg (one microkilogram).
```
src: https://en.wikipedia.org/wiki/Kilogram#SI_multiples

**Comment by martinlindhe** [comment]
@parnmatt please have a look at this change; https://github.com/martinlindhe/unit/commit/27761a06d113bb4a8dd0ce662e84a5c57a3a200f#diff-02940c41e6732b30515bfeaee9813076

It keeps the internal unit as Gram, while having 1e0 Mass = 1 Kilogram. This way calculated values will be roughly the same, possible with rounding variations.

**Comment by parnmatt** [comment]
Sorry, my work got in the way of doing this.

Yes I agree that was along the lines I was thinking, as it keeps the SI prefix inline with exponent.

:+1:
